/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/bh3': RouteRecordInfo<
      '/albums/bh3',
      '/albums/bh3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/vsinger': RouteRecordInfo<
      '/albums/vsinger',
      '/albums/vsinger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2026': RouteRecordInfo<
      '/posts/2026',
      '/posts/2026',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fix-winre': RouteRecordInfo<
      '/posts/fix-winre',
      '/posts/fix-winre',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/guide': RouteRecordInfo<
      '/posts/guide',
      '/posts/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hi': RouteRecordInfo<
      '/posts/hi',
      '/posts/hi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/image-hosting': RouteRecordInfo<
      '/posts/image-hosting',
      '/posts/image-hosting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/jetbrains-patch': RouteRecordInfo<
      '/posts/jetbrains-patch',
      '/posts/jetbrains-patch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/jetbrains-reset': RouteRecordInfo<
      '/posts/jetbrains-reset',
      '/posts/jetbrains-reset',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/life': RouteRecordInfo<
      '/posts/life',
      '/posts/life',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/notes': RouteRecordInfo<
      '/posts/notes',
      '/posts/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python/': RouteRecordInfo<
      '/posts/python/',
      '/posts/python',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python/python-using-selenium-on-edge': RouteRecordInfo<
      '/posts/python/python-using-selenium-on-edge',
      '/posts/python/python-using-selenium-on-edge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python/selenium': RouteRecordInfo<
      '/posts/python/selenium',
      '/posts/python/selenium',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/site-favourites': RouteRecordInfo<
      '/posts/site-favourites',
      '/posts/site-favourites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test/': RouteRecordInfo<
      '/posts/test/',
      '/posts/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test/included': RouteRecordInfo<
      '/posts/test/included',
      '/posts/test/included',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tools': RouteRecordInfo<
      '/posts/tools',
      '/posts/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/virtual-machine': RouteRecordInfo<
      '/posts/virtual-machine',
      '/posts/virtual-machine',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vsinger': RouteRecordInfo<
      '/posts/vsinger',
      '/posts/vsinger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wiki': RouteRecordInfo<
      '/posts/wiki',
      '/posts/wiki',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yolov8': RouteRecordInfo<
      '/posts/yolov8',
      '/posts/yolov8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'pages/albums/bh3.md': {
      routes:
        | '/albums/bh3'
      views:
        | never
    }
    'pages/albums/vsinger.md': {
      routes:
        | '/albums/vsinger'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/2026.md': {
      routes:
        | '/posts/2026'
      views:
        | never
    }
    'pages/posts/fix-winre.md': {
      routes:
        | '/posts/fix-winre'
      views:
        | never
    }
    'pages/posts/guide.md': {
      routes:
        | '/posts/guide'
      views:
        | never
    }
    'pages/posts/hi.md': {
      routes:
        | '/posts/hi'
      views:
        | never
    }
    'pages/posts/image-hosting.md': {
      routes:
        | '/posts/image-hosting'
      views:
        | never
    }
    'pages/posts/jetbrains-patch.md': {
      routes:
        | '/posts/jetbrains-patch'
      views:
        | never
    }
    'pages/posts/jetbrains-reset.md': {
      routes:
        | '/posts/jetbrains-reset'
      views:
        | never
    }
    'pages/posts/life.md': {
      routes:
        | '/posts/life'
      views:
        | never
    }
    'pages/posts/notes.md': {
      routes:
        | '/posts/notes'
      views:
        | never
    }
    'pages/posts/python/index.md': {
      routes:
        | '/posts/python/'
      views:
        | never
    }
    'pages/posts/python/python-using-selenium-on-edge.md': {
      routes:
        | '/posts/python/python-using-selenium-on-edge'
      views:
        | never
    }
    'pages/posts/python/selenium.md': {
      routes:
        | '/posts/python/selenium'
      views:
        | never
    }
    'pages/posts/site-favourites.md': {
      routes:
        | '/posts/site-favourites'
      views:
        | never
    }
    'pages/posts/test/index.md': {
      routes:
        | '/posts/test/'
      views:
        | never
    }
    'pages/posts/test/included.md': {
      routes:
        | '/posts/test/included'
      views:
        | never
    }
    'pages/posts/tools.md': {
      routes:
        | '/posts/tools'
      views:
        | never
    }
    'pages/posts/virtual-machine.md': {
      routes:
        | '/posts/virtual-machine'
      views:
        | never
    }
    'pages/posts/vsinger.md': {
      routes:
        | '/posts/vsinger'
      views:
        | never
    }
    'pages/posts/wiki.md': {
      routes:
        | '/posts/wiki'
      views:
        | never
    }
    'pages/posts/yolov8.md': {
      routes:
        | '/posts/yolov8'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
