/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/dissertation': RouteRecordInfo<'/posts/dissertation', '/posts/dissertation', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/image-hosting': RouteRecordInfo<'/posts/image-hosting', '/posts/image-hosting', Record<never, never>, Record<never, never>>,
    '/posts/informal-essay': RouteRecordInfo<'/posts/informal-essay', '/posts/informal-essay', Record<never, never>, Record<never, never>>,
    '/posts/jetbrains-patch': RouteRecordInfo<'/posts/jetbrains-patch', '/posts/jetbrains-patch', Record<never, never>, Record<never, never>>,
    '/posts/jetbrains-reset': RouteRecordInfo<'/posts/jetbrains-reset', '/posts/jetbrains-reset', Record<never, never>, Record<never, never>>,
    '/posts/python/': RouteRecordInfo<'/posts/python/', '/posts/python', Record<never, never>, Record<never, never>>,
    '/posts/python/python-using-selenium-on-edge': RouteRecordInfo<'/posts/python/python-using-selenium-on-edge', '/posts/python/python-using-selenium-on-edge', Record<never, never>, Record<never, never>>,
    '/posts/python/selenium': RouteRecordInfo<'/posts/python/selenium', '/posts/python/selenium', Record<never, never>, Record<never, never>>,
    '/posts/sdau': RouteRecordInfo<'/posts/sdau', '/posts/sdau', Record<never, never>, Record<never, never>>,
    '/posts/test/': RouteRecordInfo<'/posts/test/', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/tools': RouteRecordInfo<'/posts/tools', '/posts/tools', Record<never, never>, Record<never, never>>,
    '/posts/virtual-machine': RouteRecordInfo<'/posts/virtual-machine', '/posts/virtual-machine', Record<never, never>, Record<never, never>>,
    '/posts/vsinger': RouteRecordInfo<'/posts/vsinger', '/posts/vsinger', Record<never, never>, Record<never, never>>,
    '/posts/wiki': RouteRecordInfo<'/posts/wiki', '/posts/wiki', Record<never, never>, Record<never, never>>,
    '/posts/wt': RouteRecordInfo<'/posts/wt', '/posts/wt', Record<never, never>, Record<never, never>>,
    '/posts/yolov8': RouteRecordInfo<'/posts/yolov8', '/posts/yolov8', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
