/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/bh3': RouteRecordInfo<'/albums/bh3', '/albums/bh3', Record<never, never>, Record<never, never>>,
    '/albums/vsinger': RouteRecordInfo<'/albums/vsinger', '/albums/vsinger', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/deepseek': RouteRecordInfo<'/posts/deepseek', '/posts/deepseek', Record<never, never>, Record<never, never>>,
    '/posts/fix-winre': RouteRecordInfo<'/posts/fix-winre', '/posts/fix-winre', Record<never, never>, Record<never, never>>,
    '/posts/guide': RouteRecordInfo<'/posts/guide', '/posts/guide', Record<never, never>, Record<never, never>>,
    '/posts/hi': RouteRecordInfo<'/posts/hi', '/posts/hi', Record<never, never>, Record<never, never>>,
    '/posts/image-hosting': RouteRecordInfo<'/posts/image-hosting', '/posts/image-hosting', Record<never, never>, Record<never, never>>,
    '/posts/jetbrains-patch': RouteRecordInfo<'/posts/jetbrains-patch', '/posts/jetbrains-patch', Record<never, never>, Record<never, never>>,
    '/posts/jetbrains-reset': RouteRecordInfo<'/posts/jetbrains-reset', '/posts/jetbrains-reset', Record<never, never>, Record<never, never>>,
    '/posts/life': RouteRecordInfo<'/posts/life', '/posts/life', Record<never, never>, Record<never, never>>,
    '/posts/notes': RouteRecordInfo<'/posts/notes', '/posts/notes', Record<never, never>, Record<never, never>>,
    '/posts/python/': RouteRecordInfo<'/posts/python/', '/posts/python', Record<never, never>, Record<never, never>>,
    '/posts/python/python-using-selenium-on-edge': RouteRecordInfo<'/posts/python/python-using-selenium-on-edge', '/posts/python/python-using-selenium-on-edge', Record<never, never>, Record<never, never>>,
    '/posts/python/selenium': RouteRecordInfo<'/posts/python/selenium', '/posts/python/selenium', Record<never, never>, Record<never, never>>,
    '/posts/site-favourites': RouteRecordInfo<'/posts/site-favourites', '/posts/site-favourites', Record<never, never>, Record<never, never>>,
    '/posts/test/': RouteRecordInfo<'/posts/test/', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/test/included': RouteRecordInfo<'/posts/test/included', '/posts/test/included', Record<never, never>, Record<never, never>>,
    '/posts/tools': RouteRecordInfo<'/posts/tools', '/posts/tools', Record<never, never>, Record<never, never>>,
    '/posts/virtual-machine': RouteRecordInfo<'/posts/virtual-machine', '/posts/virtual-machine', Record<never, never>, Record<never, never>>,
    '/posts/vsinger': RouteRecordInfo<'/posts/vsinger', '/posts/vsinger', Record<never, never>, Record<never, never>>,
    '/posts/wiki': RouteRecordInfo<'/posts/wiki', '/posts/wiki', Record<never, never>, Record<never, never>>,
    '/posts/yolov8': RouteRecordInfo<'/posts/yolov8', '/posts/yolov8', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
